services:
    server_01:
        build: .
        container_name: server_01
        environment:
            MYSQL_DB_HOST: mysql_01
            MYSQL_DB_PORT: 3306
            MYSQL_DB_USER: root
            MYSQL_DB_PASSWORD: root
            NODE_ID: 1
        depends_on:
            mysql_01:
                condition: service_healthy
        ports:
            - "8080:8080"
        networks:
            custom_net:
                ipv4_address: 172.25.0.2
    server_02:
        build: .
        container_name: server_02
        environment:
            MYSQL_DB_HOST: mysql_02
            MYSQL_DB_PORT: 3306
            MYSQL_DB_USER: root
            MYSQL_DB_PASSWORD: root
            NODE_ID: 2
        depends_on:
            mysql_02:
                condition: service_healthy
        ports:
            - "8081:8080"
        networks:
            custom_net:
                ipv4_address: 172.25.0.3
    server_03:
        build: .
        container_name: server_03
        environment:
            MYSQL_DB_HOST: mysql_03
            MYSQL_DB_PORT: 3306
            MYSQL_DB_USER: root
            MYSQL_DB_PASSWORD: root
            NODE_ID: 3
        depends_on:
            mysql_03:
                condition: service_healthy
        ports:
            - "8082:8080"
        networks:
            custom_net:
                ipv4_address: 172.25.0.4
    mysql_01:
        image: mysql:8.0
        container_name: mysql_01
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3307:3306"
        volumes:
            - mysql_data1:/var/lib/mysql
        networks:
            custom_net:
                ipv4_address: 172.25.0.12
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
    mysql_02:
        image: mysql:8.0
        container_name: mysql_02
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3308:3306"
        volumes:
            - mysql_data2:/var/lib/mysql
        networks:
            custom_net:
                ipv4_address: 172.25.0.13
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
    mysql_03:
        image: mysql:8.0
        container_name: mysql_03
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3309:3306"
        volumes:
            - mysql_data3:/var/lib/mysql
        networks:
            custom_net:
                ipv4_address: 172.25.0.14
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
                

networks:
    custom_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.25.0.0/16

volumes:
    mysql_data1:
    mysql_data2:
    mysql_data3: